WIP: PMM-9081-create-copyToClipboard-component: add component
percona-platform/core-ui pull request #29
Opened 2021-11-01 14:47 UTC by solovevayaroslavna

2021-11-02 12:32 UTC, atymchuk requested changes

2021-11-02 12:32 UTC, atymchuk commented on src/components/CopyToClipboard/CopyToClipboard.test.tsx
> +  test('clicking on the button show the tooltip', async () => {
```suggestion
  test('clicking on the button should show the tooltip', async () => {
```

2021-11-02 12:32 UTC, atymchuk commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +  const copyToClipboard = useCallback(() => textContainer.current?.textContent? textContainer.current?.textContent : '', [textContainer]);
```suggestion
  const copyToClipboard = useCallback(() => textContainer.current?.textContent ? textContainer.current?.textContent : '', [textContainer]);
```

2021-11-02 12:32 UTC, atymchuk commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +    setTimeout(() => setVisible(false), 2000);
Can't we pass the timeout of 2000 to the tooltip (i.e. popper)? I thought it was configurable...

2021-11-02 12:32 UTC, atymchuk commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +    setTooltipText('Text not copied to clipboard');
```suggestion
    setTooltipText('Couldn\'t copy text to clipboard');
```

2021-11-02 12:32 UTC, atymchuk commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +    setTimeout(() => setVisible(false), 2000);
Another question: if the user navigates away from the pages, won't setting the state on a destroyed component generate an error? I think we have to couple it with `useEffect`.

2021-11-02 12:36 UTC, atymchuk requested changes

2021-11-02 12:36 UTC, atymchuk commented on src/components/CopyToClipboard/CopyToClipboard.test.tsx
> +  await act(async () => {
Given the reasons stated in https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#wrapping-things-in-act-unnecessarily, the act function above may not be necessary.

2021-11-05 17:11 UTC, tiagomotasantos requested changes

2021-11-05 17:11 UTC, tiagomotasantos commented on src/components/CopyToClipboard/CopyToClipboard.styles.ts
> +      z-index: 1;
Can we use any of zIndex variables from grafana theme?

2021-11-05 17:11 UTC, tiagomotasantos commented on src/components/CopyToClipboard/CopyToClipboard.test.tsx
> +const DATA_QA_TOOLTIP='tooltip';
DATA_TESTID

2021-11-05 17:11 UTC, tiagomotasantos commented on src/components/CopyToClipboard/CopyToClipboard.test.tsx
> +    await asyncClick(button);
Why we need async click? Firing a click event on it's own doesn't work?

2021-11-05 17:11 UTC, tiagomotasantos commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +export const CopyToClipboard: FC<ClipboardIconButtonProps> = (props) => {
Props can be destructured here

2021-11-05 17:11 UTC, tiagomotasantos commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +  const copyToClipboard = useCallback(() => textContainer.current?.textContent? textContainer.current?.textContent : '', [textContainer]);
```suggestion
  const copyToClipboard = useCallback(() => textContainer.current?.textContent || '', [textContainer]);
```

2021-11-05 17:17 UTC, tiagomotasantos requested changes

2021-11-05 17:17 UTC, tiagomotasantos commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +  textContainer: React.MutableRefObject<any>;
We know that we will have a ref to an HTMLElement/ReactNode/ReactElement, so maybe we can be more restrictive about the type.

2021-11-15 06:49 UTC, solovevayaroslavna commented on src/components/CopyToClipboard/CopyToClipboard.test.tsx
> +  test('clicking on the button show the tooltip', async () => {
thanks, corrected

2021-11-15 06:50 UTC, solovevayaroslavna commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +  const copyToClipboard = useCallback(() => textContainer.current?.textContent? textContainer.current?.textContent : '', [textContainer]);
thanks, corrected

2021-11-15 06:53 UTC, solovevayaroslavna commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +    setTimeout(() => setVisible(false), 2000);
I checked the documentation for this library and did not see such functions, so I had to leave setTimeout. But yes, you're absolutely right! Thanks for noticing that. I took the timeout to useEffect to clear it when unmounting.

2021-11-15 06:54 UTC, solovevayaroslavna commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +    setTooltipText('Text not copied to clipboard');
thanks, corrected

2021-11-15 06:55 UTC, solovevayaroslavna commented on src/components/CopyToClipboard/CopyToClipboard.test.tsx
> +  await act(async () => {
Thanks for the article! I have corrected the tests so that they don't use act

2021-11-15 07:08 UTC, solovevayaroslavna commented on src/components/CopyToClipboard/CopyToClipboard.test.tsx
> +const DATA_QA_TOOLTIP='tooltip';
Thanks! I corrected it.  Are there any other naming rules in tests? I haven't seen DATA_TESTID anywhere else and I would like to understand why you suggested this fix.

2021-11-15 07:10 UTC, solovevayaroslavna commented on src/components/CopyToClipboard/CopyToClipboard.test.tsx
> +    await asyncClick(button);
Thanks! Alex also noticed this moment. Yes, you're absolutely right, he's not needed there. I've already corrected it.

2021-11-15 07:12 UTC, solovevayaroslavna commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +export const CopyToClipboard: FC<ClipboardIconButtonProps> = (props) => {
Thanks! Yes, it's definitely better this way)

2021-11-15 07:14 UTC, solovevayaroslavna commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +  const copyToClipboard = useCallback(() => textContainer.current?.textContent? textContainer.current?.textContent : '', [textContainer]);
Precisely! Corrected it.

2021-11-15 07:48 UTC, solovevayaroslavna commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +  textContainer: React.MutableRefObject<any>;
Unfortunately, I can't use ReactNode and ReactElement for the following reason. Only HtmlElement. 
![image](https://user-images.githubusercontent.com/90199600/141738336-1f486c8c-a45d-4d34-ad2f-1f6edb536129.png)
But if I type as HTMLElement, then another problem appears. Usually, when we declare a ref on an element, we often write (picture below) at the first declaration.
![image](https://user-images.githubusercontent.com/90199600/141740434-f8777263-5714-474b-8344-482c859955dc.png)
And this creates another problem in which we will need such typing.
![image](https://user-images.githubusercontent.com/90199600/141740659-5904269d-b516-41ca-9a8a-0a37a05bf52a.png)
It seemed to me that this could become a limitation, so I left any for the first time. But now, I read a little more about ref and it seems to me that we can leave HTMLElement |  null in this form. What do you think about this typing?

2021-11-15 08:19 UTC, solovevayaroslavna commented on src/components/CopyToClipboard/CopyToClipboard.styles.ts
> +      z-index: 1;
Thanks! I corrected it. 
![image](https://user-images.githubusercontent.com/90199600/141746461-d85f6aa1-fd41-467f-a305-e623081841d7.png)

2021-11-15 10:21 UTC, tiagomotasantos commented on src/components/CopyToClipboard/CopyToClipboard.test.tsx
> +const DATA_QA_TOOLTIP='tooltip';
We use data-testid now instead of data-qa. So let's keep the variable names consistent. I see that there is still DATA_QA_BUTTON in the code so pls replace it with DATA_TESTID. Also "TESTID" is joined instead of "TEST_ID". This is convention.

2021-11-15 10:23 UTC, tiagomotasantos commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +  textContainer: React.MutableRefObject<any>;
`HTMLElement | null` is perfect!

2021-11-15 10:26 UTC, tiagomotasantos requested changes

2021-11-15 10:26 UTC, tiagomotasantos commented on src/components/CopyToClipboard/CopyToClipboard.test.tsx
> +const DATA_QA_BUTTON='clipboard-button';
```suggestion
const DATA_TESTID_BUTTON='clipboard-button';
```

2021-11-15 10:26 UTC, tiagomotasantos commented on src/components/CopyToClipboard/CopyToClipboard.test.tsx
> +const DATA_TEST_ID='tooltip';
```suggestion
const DATA_TESTID_TOOLTIP='tooltip';
```

2021-11-15 10:26 UTC, tiagomotasantos commented on src/components/Table/Table.tsx
> +import { Overlay } from '..';
```suggestion
import { Overlay } from '../components';
```

Not sure if it's the right path but something like this would be more explicit

2021-11-15 11:12 UTC, atymchuk commented on src/components/Label/Label.tsx
> +        {label}{required ? ' *' : ''}
👍

2021-11-15 11:13 UTC, atymchuk approved these changes

2021-11-15 11:59 UTC, solovevayaroslavna commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +  textContainer: React.MutableRefObject<any>;
Made an edit

2021-11-15 11:59 UTC, solovevayaroslavna commented on src/components/CopyToClipboard/CopyToClipboard.test.tsx
> +const DATA_QA_BUTTON='clipboard-button';
Made an edit

2021-11-15 11:59 UTC, solovevayaroslavna commented on src/components/CopyToClipboard/CopyToClipboard.test.tsx
> +const DATA_TEST_ID='tooltip';
Made an edit

2021-11-15 12:03 UTC, solovevayaroslavna commented on src/components/Table/Table.tsx
> +import { Overlay } from '..';
The development environment tells me that this will be such a solution, so I fixed it a little differently
![image](https://user-images.githubusercontent.com/90199600/141778918-ae84c34c-f3a5-4dc8-9f63-cd85b7b1a8ad.png)

2021-11-15 12:08 UTC, solovevayaroslavna commented on src/components/Label/Label.tsx
> +        {label}{required ? ' *' : ''}
These are not my changes, they appeared after I merged main into my branch, which is strange because.. as far as I know, after I pull main to my brunch, no other people's changes should be in my changes. Maybe I pulled the wrong main branch?  I don't understand why I get other changes in my PR, can you check this, please?

2021-11-15 12:08 UTC, tiagomotasantos commented on src/components/Table/Table.tsx
> +import { Overlay } from '..';
Awesome just put it in singlequotes to fix the linting

2021-11-15 12:18 UTC, fabio-silva commented on src/components/Label/Label.tsx
> +        {label}{required ? ' *' : ''}
These were my changes from another PR. But this is weird, by checking main, there's actually no change because you've already merged, but somehow the PR is not fully updated. I don't think it's your problem here, something with Github

2021-11-15 12:28 UTC, atymchuk commented on src/components/Label/Label.tsx
> +        {label}{required ? ' *' : ''}
No, not really github ))

2021-11-15 12:42 UTC, atymchuk commented on src/components/Table/Table.tsx
> +import { Overlay } from '..';
Fixed

2021-11-15 12:43 UTC, atymchuk commented on src/components/Label/Label.tsx
> +        {label}{required ? ' *' : ''}
Fixed - those are gone. Rebase is allmighty :)

2021-11-15 12:49 UTC, tiagomotasantos approved these changes

2021-11-18 12:52 UTC, merged