SAAS-540 add max length validator
percona-platform/core-ui pull request #3
Opened 2021-04-27 18:03 UTC by nicolalamacchia

2021-04-27 20:29 UTC, atymchuk commented on src/shared/validators/maxLength.test.ts
> +    const errorMessage = `Must contain at least ${length} characters`;
The error message and the test assertions suggest that it should be a `minLength`  rather than `maxLength`  validator.
I'm a bit confused with the above.

2021-04-27 20:36 UTC, nicolalamacchia commented on src/shared/validators/maxLength.test.ts
> +    const errorMessage = `Must contain at least ${length} characters`;
Fixed the error message

2021-04-28 08:44 UTC, fabio-silva requested changes

2021-04-28 08:44 UTC, fabio-silva commented on src/shared/validators/maxLength.test.ts
> +  it('should return an error if the string length is less than required', () => {
```suggestion
  it('should return an error if the string length is greater than required', () => {
```

2021-04-28 12:05 UTC, atymchuk requested changes

2021-04-28 12:05 UTC, atymchuk commented on src/shared/validators/maxLength.test.ts
> +  it('should return undefined if the string length is equal to or less than required', () => {
the word `required` he is misleading, since we also have a `required` validator.
```suggestion
  it('should return undefined if the string length is equal to or less than maxLength parameter', () => {
```

2021-04-28 12:05 UTC, atymchuk commented on src/shared/validators/maxLength.test.ts
> +  it('should return an error if the string length is less than required', () => {
```suggestion
  it('should return an error if the string length is less than maxLength parameter', () => {
```

2021-04-28 12:09 UTC, atymchuk commented
Does it make sense to check for `null/undefined` (ex: https://github.com/percona-platform/core-ui/blob/main/src/shared/validators/minLength.ts#L4) to make it more reliable?

2021-04-28 15:08 UTC, nicolalamacchia commented on src/shared/validators/maxLength.test.ts
> +  it('should return an error if the string length is less than required', () => {
Done

2021-04-28 15:08 UTC, nicolalamacchia commented on src/shared/validators/maxLength.test.ts
> +  it('should return undefined if the string length is equal to or less than required', () => {
Done

2021-04-28 15:08 UTC, nicolalamacchia commented on src/shared/validators/maxLength.test.ts
> +  it('should return an error if the string length is less than required', () => {
this less than, greater than thing got me confused 😅  Done

2021-04-28 15:13 UTC, fabio-silva approved these changes

2021-04-28 15:22 UTC, atymchuk approved these changes

2021-04-28 15:52 UTC, merged