increase line-height for checkbox label
percona-platform/core-ui pull request #32
Opened 2021-11-10 10:47 UTC by fabio-silva

2021-11-11 09:50 UTC, atymchuk commented on src/components/Checkbox/Checkbox.styles.ts
> -      padding-left: ${spacing.formSpacingBase}px;
I wonder if we no longer need the left padding to have some space between the checkbox and the label? Do you have a preview of what it will look like after the mod?

2021-11-11 10:05 UTC, fabio-silva commented on src/components/Checkbox/Checkbox.styles.ts
> -      padding-left: ${spacing.formSpacingBase}px;
@atymchuk  Added the screenshot. I've removed these lines because the `label` key wasn't actually being used after i moved everything to `Label` in the previous version.

2021-11-12 16:25 UTC, tiagomotasantos requested changes

2021-11-12 16:25 UTC, tiagomotasantos commented on src/components/Checkbox/Checkbox.styles.ts
> +    line-height: ${theme.typography.lineHeight.md};
Missing some spacing here

2021-11-12 21:06 UTC, atymchuk commented on src/components/Checkbox/Checkbox.styles.ts
> -      padding-left: ${spacing.formSpacingBase}px;
Got it!

2021-11-12 22:09 UTC, atymchuk approved these changes

2021-11-17 18:03 UTC, tiagomotasantos approved these changes

2021-11-17 20:42 UTC, merged