SAAS-469: chips/tags component
percona-platform/core-ui pull request #35
Opened 2022-01-06 12:08 UTC by fabio-silva

https://jira.percona.com/browse/SAAS-469

Implementation details:

- Two components: `Chip` and `ChipAreaInputField`. The former can be used as a standalone component (`isRemovable` prop allows a chip to be removed). As for the latter, it's useful to be used within a form (react-final-form);
- Rules for `ChipAreaInputField`: 
    - No duplicate tags allowed (tags are usually unique, and it makes it easier for us to remove a tag without the need to track them using IDs or other hacky methods)
    - No empty tags allowed;
    - `minTags` validator can be used to make sure it's not empty;
    - On form submission, values are saved in a string array on the form (e.g. `{tags: ["tag1", "tag2"]}`);
- Clicking on the container will automatically focus the input.

![Screen Recording 2022-01-06 at 11 51 48](https://user-images.githubusercontent.com/4190654/148380822-968e73e2-35e4-4a79-a218-ac185b5f79de.gif)

2022-01-10 01:27 UTC, atymchuk commented
@fabio-silva can we have an svg clear (cross) icon with tiny lines instead of that bootstrap icon?

2022-01-10 01:32 UTC, atymchuk requested changes

2022-01-10 01:32 UTC, atymchuk commented on src/components/Chip/Chip.styles.ts
> +    border-radius: calc(${height.sm}px/2);
I would propose:
1/ much less left/right padding; the current padding looks a bit too large;
2/ a lower value for border-radius; the current radius makes it look too roundish

2022-01-10 15:48 UTC, tiagomotasantos requested changes
👏👏👏👏

2022-01-11 09:07 UTC, solovevayaroslavna commented on src/components/Chip/Chip.styles.ts
> +    border-radius: calc(${height.sm}px/2);
I agree with Alex, I also visually want to see the left and right padding less than they are now.

2022-01-11 11:38 UTC, fabio-silva commented on src/components/Chip/Chip.styles.ts
> +    border-radius: calc(${height.sm}px/2);
Thanks guys. Just applied the changes, please check the last screenshots

2022-01-11 11:39 UTC, fabio-silva commented on src/shared/validators/minTags.ts
> +  return `Must contain at least ${length} tags`;
good one!

2022-01-11 11:41 UTC, tiagomotasantos approved these changes

2022-01-11 11:46 UTC, fabio-silva commented
> @fabio-silva can we have an svg clear/cross icon with tiny lines instead of that aged font-awesome icon?

Yep, new screenshot added

2022-01-11 16:08 UTC, atymchuk commented
> > @fabio-silva can we have an svg clear/cross icon with tiny lines instead of that aged font-awesome icon?
> 
> Yep, new screenshot added

Madonna, it looks so much cleaner! Aaaawesome, thanks!

2022-01-11 16:12 UTC, atymchuk approved these changes

2022-01-12 15:37 UTC, merged