Update to Grafana 8
percona-platform/core-ui pull request #37
Opened 2022-01-20 14:58 UTC by fabio-silva

2022-01-25 16:52 UTC, tiagomotasantos requested changes

2022-01-25 16:52 UTC, tiagomotasantos commented on src/components/CopyToClipboard/CopyToClipboard.styles.ts
> +export const getStyles = ({ v1}: GrafanaTheme2) => {
```suggestion
export const getStyles = ({ v1 }: GrafanaTheme2) => {
```

2022-01-25 16:52 UTC, tiagomotasantos commented on src/setupTests.ts
> +});
Missing EOF line

2022-01-26 11:20 UTC, fabio-silva commented on src/components/CopyToClipboard/CopyToClipboard.styles.ts
> +export const getStyles = ({ v1}: GrafanaTheme2) => {
👍

2022-01-26 11:20 UTC, fabio-silva commented on src/setupTests.ts
> +});
👍

2022-01-26 14:13 UTC, tiagomotasantos approved these changes

2022-01-27 09:54 UTC, merged